# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByQmu_frxuqBohkaAuFlpADyIcY8Wg6O
"""

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country']=="Afghanistan")]
print(filtr)

filtr_count = filtr.shape[0]
print(f"Filtrdan o'tganlar soni: {filtr_count}")

filtr=df[(df['Country']=="Albania")]
print(filtr)

filtr_count = filtr.shape[0]
print(f"Filtrdan o'tganlar soni: {filtr_count}")

filtr=df[(df['Country']=="Algeria")]
print(filtr)

filtr_count = filtr.shape[0]
print(f"Filtrdan o'tganlar soni: {filtr_count}")